### ISSUE TITLE
Not able to launch ununi 

### ISSUE THREAD

**Issue by bemnet4u** [andrew-pa/ununi#1]
I downloaded the binary and I tried running it on windows 7. I think its crashing. 
I tried running it from command line console to but was not able to see any error message. Try adding some diagnostic logs in the std out so we know what is going on.

**Comment by andrew-pa** [comment]
Hm here's a release build of the latest release that worked in my Windows 7 VM:
[ununi (2).zip](https://github.com/andrew-pa/ununi/files/1335585/ununi.2.zip)

Notably it seems that Windows 7's Unicode support in places is less than stellar so there are likely a lot of missing characters, as the index is build against the latest Unicode standard.
